// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFSSEKT-ZYg5kYPlwBwiWh8q3UZsEIcec',
    appId: '1:1029109934862:web:753b80ae38618719c5c55f',
    messagingSenderId: '1029109934862',
    projectId: 'compartimosgastosapp',
    authDomain: 'compartimosgastosapp.firebaseapp.com',
    storageBucket: 'compartimosgastosapp.firebasestorage.app',
    measurementId: 'G-GBDJ0RHTLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkjvICetJbIaSLirQqB7eIPCo6A0Vxw-k',
    appId: '1:1029109934862:android:1224c6f381cefbc3c5c55f',
    messagingSenderId: '1029109934862',
    projectId: 'compartimosgastosapp',
    storageBucket: 'compartimosgastosapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMIKoX-LS9EWZvbuGPrk_g56B1ZL27Jvc',
    appId: '1:1029109934862:ios:ea10a7c0253d8634c5c55f',
    messagingSenderId: '1029109934862',
    projectId: 'compartimosgastosapp',
    storageBucket: 'compartimosgastosapp.firebasestorage.app',
    iosBundleId: 'josebyteando.compartimosgastos.compartimosGastos',
  );
}
